set nocompatible

" required for Vundle
filetype off
set rtp+=~/dotfiles/vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
""" Insert Vundle plugins here """
" Plugin 'tmhedberg/SimpylFold'
" Plugin 'vim-scripts/indentpython.vim'
" Plugin 'scrooloose/syntastic'
" Following plug-in adds PEP8 checking for python
" Plugin 'nvie/vim-flake8'
" Following plug-in adds terminal colorscheme Zenburn
" Plugin 'jnurmine/Zenburn'
" Following plug-in adds gui colorscheme Solarized
" Plugin 'altercation/vim-colors-solarized'
" Plugin 'scrooloose/nerdtree'
" Plugin 'Valloric/YouCompleteMe'
""" End Vundle plugins here """
call vundle#end()
filetype plugin indent on " allow customized settings, plugins and indentation settings based on file type

set incsearch " incremental search

set ignorecase " case insensitive search ...
set smartcase  " ... unless search includes capital letters
 
set scrolloff=2 " keep 2 lines of context around cursor 
  
set visualbell " no beeps
set noerrorbells " no beeps
                
set title " terminal window shows title of file

set hidden

" -- Following lines allow you to view carriage returns (set binary) and
"  list chars (set listchars -> set list) such as tabs, newlines, etc. --
set listchars=tab:>-,eol:$
" set binary
" set list
" command -nargs=0 Hidden :e ++ff=unix " Toggle displaying hidden characters (right now only turns on carriage returns, need to add toggling and displaying list chars as well)

" Set custom mappings 
inoremap ;; <Esc>
vnoremap ;; <Esc> 
noremap <C-S>	:w<CR>
vnoremap <C-S>	<Esc>:w<CR><C-V>
inoremap <C-S>	<Esc>:w<CR>a
noremap L $
noremap H ^
" nnoremap <Esc> :noh<return><Esc> " may cause a bug where vim starts in i-mode
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv
nnoremap <Tab> >>
nnoremap <S-Tab> <<
command -nargs=* Te tabedit <args>
map <C-a> GVgg
set backspace=indent,eol,start
" Enable folding with the spacebar
nnoremap <space> za

" Hitting enter on keyboard in command mode creates a newline
nmap <CR> ko<Esc> 
" Hitting backspace on keyboard deletes an empty line
nmap <BS> _dd

" Color modifications

if &t_Co >= 256 || has("gui_running")
	highlight Normal ctermbg=white
	set background=light
	colorscheme developer 
endif

if &t_Co > 2 || has("gui_running")
	" switch syntax highlighting on
        " colorscheme evening
	let python_highlight_all=1
	syntax on
endif

" Enable folding"
set foldmethod=indent
set foldlevel=99

" For YouCompleteMe, close window after completing, and making it easy to goto definitions

